export interface Config {
  geminiApiKey: string;
  modelName: string;
  inboxDir: string;      // "mesh-out" (incoming to ranger)
  outboxDir: string;     // "outbox" (drafts generated by ranger)
  meshInDir: string;     // "mesh-in" (weather advisory injected back)
  weatherLat: number;    // Open-Meteo latitude
  weatherLon: number;    // Open-Meteo longitude
  logFile: string;       // "ranger.log"
}
